
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springai
    username: postgres
    password: 123456



#langchain4j:
#  open-ai:
#    chat-model:
#      api-key: sk-xx
#      model-name: qwen-turbo
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1

langchain4j:
## 灵积大模型
#  community:
#    dashscope:
#      chat-model:
#        api-key: ${DASHSCOPE_API_KEY}
##        model-name: deepseek-v3
#        model-name: qwen-max-latest


  ollama:
    chat-model:
      base-url: http://localhost:11434
#      model-name: llama3 # 不支持 function call
      model-name: llama3.1
    embedding-model:
      base-url: http://localhost:11434
      model-name: all-minilm

pgvector:
  database: springai
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  table: my_embeddings

search:
  api-key: ${SEARCH_API_KEY}
  engine: baidu

#logging:
#  level:
#    root: debug